import React, { useEffect, useState, useMemo } from 'react';
import { collection, onSnapshot } from 'firebase/firestore';
import { db } from '../../../config/firebase';
import { useAuth } from '../../../context/AuthContext';
import { formatPrice } from '../../../shared/utils/format';
import { intelligenceService } from '../../../shared/intelligence/services/intelligenceService';
import { knowledgeEngine } from '../../../shared/intelligence/knowledge/knowledgeEngine';
import { 
  GeminiProvider, 
  OpenAIProvider, 
  ClaudeProvider, 
  OllamaProvider, 
  DeepSeekProvider 
} from '../../../shared/intelligence/providers/aiProvider';

// UI Kit components
import Button from '../../../components/ui/Button/Button';
import Card from '../../../components/ui/Card/Card';
import Badge from '../../../components/ui/Badge/Badge';
import Tabs from '../../../components/ui/Tabs/Tabs';
import LoadingSpinner from '../../../components/ui/LoadingSpinner/LoadingSpinner';

// Lucide Icons
import { 
  Sparkles, 
  Activity, 
  TrendingUp, 
  AlertTriangle, 
  HelpCircle, 
  CheckCircle, 
  BookOpen, 
  Clock, 
  Brain, 
  Cpu, 
  Play, 
  ChevronDown, 
  ChevronUp, 
  Utensils, 
  DollarSign, 
  Users, 
  Workflow, 
  ShieldCheck,
  Send,
  Zap
} from 'lucide-react';
import toast from 'react-hot-toast';

export const OwnerIntelligence: React.FC = () => {
  const { user } = useAuth();
  const tenantId = user?.tenantId;

  // Real-time calculated state
  const [intelData, setIntelData] = useState<any | null>(null);
  const [knowledge, setKnowledge] = useState<any | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  // Active Tab
  const [activeTab, setActiveTab] = useState('advisor');

  // Explainability states for recommendations
  const [expandedRecId, setExpandedRecId] = useState<string | null>(null);

  // AI Adapter Sandbox States
  const [selectedProvider, setSelectedProvider] = useState<string>('gemini');
  const [sandboxPrompt, setSandboxPrompt] = useState<string>('Suggest a weekend promotion to increase dining ticket totals.');
  const [sandboxResponse, setSandboxResponse] = useState<any | null>(null);
  const [isSandboxRunning, setIsSandboxRunning] = useState(false);

  // Subscribe and compile intelligence payload
  useEffect(() => {
    if (!tenantId) return;

    setIsLoading(true);

    // Initial load
    const loadData = async () => {
      try {
        const payload = await intelligenceService.compileIntelligence(tenantId);
        setIntelData(payload);
        
        const kl = await knowledgeEngine.getRestaurantKnowledge(tenantId);
        setKnowledge(kl);
      } catch (err) {
        console.error(err);
        toast.error('Failed to compile restaurant intelligence context.');
      } finally {
        setIsLoading(false);
      }
    };

    loadData();

    // Set up subscription to refresh intelligence on orders/inventory modifications
    const unsubOrders = onSnapshot(collection(db, 'restaurants', tenantId, 'orders'), () => {
      loadData();
    });

    const unsubInv = onSnapshot(collection(db, 'restaurants', tenantId, 'inventory'), () => {
      loadData();
    });

    return () => {
      unsubOrders();
      unsubInv();
    };
  }, [tenantId]);

  // AI Providers list
  const providers = {
    gemini: new GeminiProvider(),
    openai: new OpenAIProvider(),
    claude: new ClaudeProvider(),
    ollama: new OllamaProvider(),
    deepseek: new DeepSeekProvider()
  };

  // Run AI Sandbox model triggers
  const handleRunAISandbox = async () => {
    if (!intelData?.context) return;
    setIsSandboxRunning(true);
    setSandboxResponse(null);

    const providerObj = (providers as any)[selectedProvider];
    toast.loading(`Querying mock AI Provider: ${providerObj.name}...`, { id: 'ai-sandbox' });

    setTimeout(async () => {
      try {
        const res = await providerObj.generateResponse(sandboxPrompt, intelData.context);
        setSandboxResponse(res);
        toast.success(`Mock response generated by ${res.modelUsed}`, { id: 'ai-sandbox' });
      } catch (err) {
        toast.error('Failed to run AI sandbox query.', { id: 'ai-sandbox' });
      } finally {
        setIsSandboxRunning(false);
      }
    }, 450);
  };

  if (isLoading || !intelData) {
    return (
      <div className="h-64 flex items-center justify-center">
        <LoadingSpinner label="Sensing operations datasets..." />
      </div>
    );
  }

  const { context, insights, recommendations, predictions, health, timeline } = intelData;

  // Advisor Cards stats
  const advisorStats = {
    topRecommendation: recommendations[0]?.title || 'Launch Lunch Combo deals',
    biggestRisk: context.lowStockItemsCount > 0 ? `${context.lowStockItemsCount} ingredients low or critical` : 'None logged',
    biggestOpportunity: 'Weekend Paneer sales are projected to spike by 28%.'
  };

  return (
    <div className="space-y-6 text-left select-none antialiased">
      
      {/* HEADER BLOCK */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-display font-extrabold text-textPearl flex items-center gap-2">
            <Brain className="w-7 h-7 text-primary" />
            <span>Restaurant Intelligence Engine</span>
          </h1>
          <p className="text-xs text-mutedAsh font-semibold">The operations brain, analyzing real-time parameters to compile forecasts and recommend decisions.</p>
        </div>
      </div>

      {/* TABS MENU */}
      <Tabs
        activeTabId={activeTab}
        onTabChange={setActiveTab}
        tabs={[
          { id: 'advisor', label: 'Executive Advisor', icon: ShieldCheck },
          { id: 'insights', label: 'Explainable Insights', icon: Activity },
          { id: 'predictions', label: 'Predictions', icon: TrendingUp },
          { id: 'memory', label: 'Memory profile', icon: Cpu },
          { id: 'knowledge', label: 'Knowledge Base', icon: BookOpen },
          { id: 'sandbox', label: 'Future AI Sandbox', icon: Zap },
          { id: 'timeline', label: 'Timeline logs', icon: Workflow }
        ]}
      />

      {/* 1. Advisor Tab */}
      {activeTab === 'advisor' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-3 relative overflow-hidden">
              <div className="absolute right-3.5 top-3.5 text-primary/10">
                <Sparkles className="w-12 h-12" />
              </div>
              <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider block">Today's Top Recommendation</span>
              <h3 className="text-base font-bold text-textPearl mt-1.5">{advisorStats.topRecommendation}</h3>
              <p className="text-[10.5px] text-slate-500 font-semibold mt-1">Suggested action: {recommendations[0]?.action || 'Add new menu bundles'}</p>
            </Card>

            <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-3 relative overflow-hidden">
              <div className="absolute right-3.5 top-3.5 text-red-500/10">
                <AlertTriangle className="w-12 h-12" />
              </div>
              <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider block">Today's Biggest Risk</span>
              <h3 className="text-base font-bold text-textPearl mt-1.5">{advisorStats.biggestRisk}</h3>
              <p className="text-[10.5px] text-slate-500 font-semibold mt-1">Replenish low stocks to prevent menu item lockouts.</p>
            </Card>

            <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-3 relative overflow-hidden">
              <div className="absolute right-3.5 top-3.5 text-emerald-500/10">
                <TrendingUp className="w-12 h-12" />
              </div>
              <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider block">Biggest Opportunity</span>
              <h3 className="text-base font-bold text-textPearl mt-1.5">{advisorStats.biggestOpportunity}</h3>
              <p className="text-[10.5px] text-slate-500 font-semibold mt-1">Leverage memory demand spikes to design marketing specials.</p>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Intelligence Health Dial */}
            <Card className="p-5 border-slate-850 bg-slate-900/30 flex flex-col items-center justify-center text-center space-y-4">
              <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider block w-full text-left">
                Intelligence score
              </h3>
              <div className="relative w-36 h-36 flex items-center justify-center">
                <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                  <circle cx="50" cy="50" r="40" stroke="#1e293b" strokeWidth="8" fill="transparent" />
                  <circle cx="50" cy="50" r="40" stroke="#f59e0b" strokeWidth="8" fill="transparent"
                    strokeDasharray={251.2}
                    strokeDashoffset={251.2 - (251.2 * health.score) / 100}
                    strokeLinecap="round"
                  />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center space-y-0.5">
                  <span className="text-3xl font-display font-extrabold text-textPearl">{health.score}</span>
                  <span className="text-[9px] text-slate-500 font-bold block uppercase tracking-widest">Points</span>
                </div>
              </div>
              <div className={`px-4.5 py-1.5 border rounded-2xl text-[11px] font-extrabold uppercase tracking-widest ${health.color}`}>
                {health.label}
              </div>
            </Card>

            {/* Context details list */}
            <Card className="lg:col-span-2 p-5 border-slate-850 bg-slate-900/30 space-y-4">
              <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
                Sensed Context Parameters
              </h3>
              <div className="grid grid-cols-2 gap-4 text-xs font-medium text-slate-450">
                <div className="flex justify-between py-1 border-b border-slate-850/40">
                  <span>Today's completed revenue:</span>
                  <strong className="text-textPearl font-mono">{formatPrice(context.revenueToday)}</strong>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-850/40">
                  <span>Completed tickets count:</span>
                  <strong className="text-textPearl font-mono">{context.ordersTodayCount} orders</strong>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-850/40">
                  <span>Average ticket value:</span>
                  <strong className="text-textPearl font-mono">{formatPrice(context.avgOrderValue)}</strong>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-850/40">
                  <span>Average kitchen prep turnaround:</span>
                  <strong className="text-textPearl font-mono">{context.avgPrepTimeMins} mins</strong>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-850/40">
                  <span>Customer reviews rating:</span>
                  <strong className="text-textPearl font-mono">{context.avgCsatRating.toFixed(1)} / 5.0</strong>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-850/40">
                  <span>Active occupied dining tables:</span>
                  <strong className="text-textPearl font-mono">{context.activeDinersCount} tables</strong>
                </div>
              </div>
            </Card>
          </div>
        </div>
      )}

      {/* 2. Insights Tab */}
      {activeTab === 'insights' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Insights items list */}
          <Card className="lg:col-span-2 p-5 border-slate-850 bg-slate-900/30 space-y-4">
            <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
              Sensed Business Insights
            </h3>
            <div className="space-y-3.5">
              {insights.map((ins: any) => (
                <div key={ins.id} className="bg-slate-950/40 p-4 border border-slate-855 rounded-xl flex items-start justify-between text-xs gap-3">
                  <div className="space-y-1">
                    <strong className="text-textPearl font-bold block">{ins.title}</strong>
                    <p className="text-[10px] text-slate-500 font-semibold">{ins.text}</p>
                    <span className="text-[9.5px] text-slate-500 block font-semibold">Module: {ins.relatedModule}</span>
                  </div>
                  {ins.impactPercent && (
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded font-mono ${
                      ins.impactPercent > 0 ? 'bg-emerald-500/10 text-emerald-450' : 'bg-red-500/10 text-red-400'
                    }`}>
                      {ins.impactPercent > 0 ? `+${ins.impactPercent}%` : `${ins.impactPercent}%`}
                    </span>
                  )}
                </div>
              ))}
            </div>
          </Card>

          {/* Recommendations explainability list */}
          <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-4">
            <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
              Explainable Recommendations
            </h3>
            <div className="space-y-3">
              {recommendations.map((rec: any) => {
                const isExpanded = expandedRecId === rec.id;
                return (
                  <div key={rec.id} className="bg-slate-950/30 border border-slate-855 rounded-xl p-3.5 text-xs select-none">
                    <div className="flex justify-between items-start gap-2">
                      <strong className="text-textPearl font-bold block">{rec.title}</strong>
                      <button 
                        onClick={() => setExpandedRecId(isExpanded ? null : rec.id)}
                        className="text-primary hover:underline text-[10px] font-bold uppercase tracking-wider shrink-0 flex items-center gap-0.5"
                      >
                        <span>Why</span>
                        {isExpanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                      </button>
                    </div>
                    <span className="text-[10px] text-slate-450 block font-semibold mt-1">Action: {rec.action}</span>
                    
                    {isExpanded && (
                      <div className="mt-3 pt-3 border-t border-slate-850/60 text-[10px] leading-relaxed text-slate-400 font-medium space-y-1.5">
                        <p><strong className="text-textPearl">Reasoning:</strong> {rec.reason}</p>
                        <p><strong className="text-textPearl">Projected Impact:</strong> {rec.impact}</p>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </Card>
        </div>
      )}

      {/* 3. Predictions Tab */}
      {activeTab === 'predictions' && (
        <div className="space-y-6">
          <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-4">
            <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
              Rule Predictions & Projections
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {predictions.map((p: any, idx: number) => (
                <div key={idx} className="bg-slate-950/45 p-4 border border-slate-855 rounded-2xl flex flex-col justify-between space-y-3.5 text-xs select-none">
                  <div className="space-y-1">
                    <div className="flex justify-between">
                      <strong className="text-textPearl font-bold text-sm block">{p.target}</strong>
                      <span className="text-[10px] font-bold text-primary font-mono">{p.confidence}% Confidence</span>
                    </div>
                    <h2 className="text-lg font-display font-extrabold text-emerald-450 mt-1">{p.predictedValue}</h2>
                  </div>
                  <p className="text-[10px] text-slate-500 font-semibold border-t border-slate-850/60 pt-2">{p.reasoning}</p>
                </div>
              ))}
            </div>
          </Card>
        </div>
      )}

      {/* 4. Memory Tab */}
      {activeTab === 'memory' && (
        <div className="space-y-6">
          <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-4">
            <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
              Sensed Operations habits memory
            </h3>
            <div className="space-y-3.5 text-xs font-medium text-slate-400">
              <div className="flex justify-between items-center py-2.5 border-b border-slate-850/40">
                <span>Busiest day of the week:</span>
                <strong className="text-textPearl font-bold">Friday dinners</strong>
              </div>
              <div className="flex justify-between items-center py-2.5 border-b border-slate-850/40">
                <span>Average completed check totals:</span>
                <strong className="text-textPearl font-mono font-bold">{formatPrice(3200)} avg</strong>
              </div>
              <div className="flex justify-between items-center py-2.5 border-b border-slate-850/40">
                <span>Lunch Peak Volume block:</span>
                <strong className="text-textPearl font-bold">12:00 - 15:00 weekdays</strong>
              </div>
              <div className="flex justify-between items-center py-2.5 border-b border-slate-850/40">
                <span>Highest item demand:</span>
                <strong className="text-textPearl font-bold">Chicken Biryani (+35% demand spikes on Sundays)</strong>
              </div>
            </div>
          </Card>
        </div>
      )}

      {/* 5. Knowledge Tab */}
      {activeTab === 'knowledge' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-4">
              <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
                Standard Recipes Proportions policy
              </h3>
              <div className="space-y-2 text-xs font-semibold text-slate-400">
                {knowledge && Object.entries(knowledge.recipes).map(([id, item]: any) => (
                  <div key={id} className="p-3 bg-slate-950/40 border border-slate-855 rounded-xl space-y-2">
                    <strong className="text-textPearl block">{item.menuItemName}</strong>
                    <div className="space-y-1">
                      {item.ingredients.map((ing: any, idx: number) => (
                        <div key={idx} className="flex justify-between text-[10.5px]">
                          <span>{ing.ingredientName}</span>
                          <span className="font-mono text-slate-500">{ing.quantity} {ing.unit}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </Card>

            <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-4">
              <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
                Kitchen & Waiter Quality SOP Targets
              </h3>
              <div className="space-y-3.5 text-xs text-slate-400">
                <div className="flex justify-between">
                  <span>Kitchen target preparation speed:</span>
                  <strong className="text-textPearl font-bold">&lt; 12 minutes</strong>
                </div>
                <div className="flex justify-between">
                  <span>Waiter service target speed:</span>
                  <strong className="text-textPearl font-bold">&lt; 5 minutes</strong>
                </div>
                <div className="flex justify-between">
                  <span>Taxes formulaGST (Simulated):</span>
                  <strong className="text-textPearl font-mono font-bold">GST 5.0%</strong>
                </div>
                <div className="flex justify-between">
                  <span>Service charge coefficients:</span>
                  <strong className="text-textPearl font-mono font-bold">SC 5.0%</strong>
                </div>
              </div>
            </Card>
          </div>
        </div>
      )}

      {/* 6. AI Adapter Sandbox Tab */}
      {activeTab === 'sandbox' && (
        <div className="space-y-6">
          <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-4">
            <div className="border-b border-slate-850/60 pb-3">
              <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider">
                Future AI Provider Sandbox (Placeholders Playground)
              </h3>
              <span className="text-[10px] text-slate-500 font-semibold block mt-0.5">Test future LLM providers response structures without making network calls.</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
              <div className="space-y-1.5">
                <label className="font-bold text-slate-500 uppercase block tracking-wider text-[9px]">Select Model Adapter</label>
                <select
                  value={selectedProvider}
                  onChange={(e) => setSelectedProvider(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-850 focus:border-primary rounded-xl p-3 text-xs font-semibold text-textPearl outline-none"
                >
                  <option value="gemini">Google Gemini Pro Adapter</option>
                  <option value="openai">OpenAI GPT-4o Adapter</option>
                  <option value="claude">Anthropic Claude 3.5 Sonnet Adapter</option>
                  <option value="ollama">Ollama Local Running Llama3 Adapter</option>
                  <option value="deepseek">DeepSeek Coder Adapter</option>
                </select>
              </div>

              <div className="space-y-1.5 md:col-span-2">
                <label className="font-bold text-slate-500 uppercase block tracking-wider text-[9px]">Query Restaurant Brain Prompt</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={sandboxPrompt}
                    onChange={(e) => setSandboxPrompt(e.target.value)}
                    placeholder="Enter prompt instruction..."
                    className="flex-1 bg-slate-950 border border-slate-850 focus:border-primary rounded-xl p-3 text-xs font-semibold text-textPearl outline-none"
                  />
                  <Button
                    onClick={handleRunAISandbox}
                    disabled={isSandboxRunning || !sandboxPrompt}
                    className="shrink-0 flex items-center gap-1"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>Query</span>
                  </Button>
                </div>
              </div>
            </div>

            {/* Sandbox Response Output JSON preview */}
            {sandboxResponse && (
              <div className="bg-slate-950/80 border border-slate-855 rounded-2xl p-5 space-y-3.5 text-xs">
                <div className="flex justify-between items-center border-b border-slate-850/60 pb-2.5">
                  <span className="text-[10px] text-emerald-450 font-bold uppercase tracking-wider flex items-center gap-1.5">
                    <CheckCircle className="w-4 h-4 text-emerald-450" />
                    Mock Resolution complete
                  </span>
                  <div className="flex space-x-3 text-[10px] text-slate-550 font-bold">
                    <span>Model: {sandboxResponse.modelUsed}</span>
                    <span>Latency: {sandboxResponse.latencyMs}ms</span>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <span className="font-bold text-textPearl uppercase tracking-wider block text-[9.5px]">AI Response Text:</span>
                  <p className="text-[11px] leading-relaxed text-slate-350 bg-slate-900/40 p-3 rounded-xl border border-slate-850/50 font-medium">
                    {sandboxResponse.text}
                  </p>
                </div>

                <div className="space-y-1.5">
                  <span className="font-bold text-textPearl uppercase tracking-wider block text-[9.5px]">Mock JSON payload:</span>
                  <pre className="text-[10px] text-slate-500 font-mono overflow-x-auto p-3.5 bg-slate-900/30 rounded-xl border border-slate-850/30">
                    {JSON.stringify(sandboxResponse, null, 2)}
                  </pre>
                </div>
              </div>
            )}
          </Card>
        </div>
      )}

      {/* 7. Timeline Tab */}
      {activeTab === 'timeline' && (
        <div className="space-y-6">
          <Card className="p-5 border-slate-850 bg-slate-900/30 space-y-4">
            <h3 className="text-xs font-bold text-textPearl uppercase tracking-wider pb-2 border-b border-slate-850/60">
              Intelligence Engine decision timeline
            </h3>
            <div className="space-y-4.5 relative pl-4 border-l border-slate-850 mt-2">
              {timeline.map((item: any) => (
                <div key={item.id} className="relative space-y-1 text-xs">
                  <div className="absolute -left-[20px] top-1.5 w-2.5 h-2.5 rounded-full bg-primary ring-4 ring-background" />
                  <div className="flex justify-between items-center">
                    <strong className="text-textPearl block font-bold">{item.title}</strong>
                    <span className="text-[10px] text-slate-550">{new Date(item.timestamp).toLocaleString()}</span>
                  </div>
                  <p className="text-[10.5px] text-slate-500 font-semibold">{item.description}</p>
                </div>
              ))}
            </div>
          </Card>
        </div>
      )}
    </div>
  );
};

export default OwnerIntelligence;
